### ISSUE TITLE
GCP LBaaS Node Type & Lifecycle Support

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-cosmo/cloudify-gcp-plugin#55]
Background:
- https://cloud.google.com/compute/docs/load-balancing/http/
- https://cloud.google.com/compute/docs/reference/latest/#GlobalForwardingRules
- https://cloud.google.com/compute/docs/reference/latest/#TargetHttpProxies
- https://cloud.google.com/compute/docs/reference/latest/#TargetHttpsProxies
- https://developers.google.com/api-client-library/python/apis/compute/v1
- https://github.com/google/google-api-python-client
- https://github.com/google/google-api-python-client/blob/master/docs/dyn/compute_v1.forwardingRules.html
- https://github.com/google/google-api-python-client/blob/master/docs/dyn/compute_v1.targetHttpProxies.html
- https://github.com/google/google-api-python-client/blob/master/docs/dyn/compute_v1.targetHttpsProxies.html

**Comment by funkyHat** [comment]
https://github.com/cloudify-cosmo/cloudify-gcp-plugin/blob/master/system_tests/resources/http_forwarding/global-https-static-ip-blueprint.yaml and https://github.com/cloudify-cosmo/cloudify-gcp-plugin/blob/master/system_tests/resources/http_forwarding/global-https-static-ip-blueprint.yaml seem to cover this. What's missing?
